### PR TITLE
fixed build on xcode 8.0 with swift 3.0

### PR DESCRIPTION
**Pull request by zhouliangshun**
error:
1.Function types cannot have argument label 'xxx'; use '_' instead
for typealias rename xxx to _xxx

2.'ErrorProtocol' has been renamed to 'Error'
rename ErrorProtocol to Error and rename inner Error to BKError

3.Method 'xxx' with Objective-C selector 'xxx' conflicts with previous declaration with the same Objective-C selector
add @nonobjc on this method

### CODE REVIEW

**Comment by rhummelmose** [comment]
@calebkleveter does your fixes overlap?

**Comment by calebkleveter** [comment]
No, there are additional changes in this PR.

**Comment by ArniDexian** [comment]
Hi, @rhummelmose will you merge it?

**Comment by rhummelmose** [comment]
Yep.

**Pull request merged**
